### ISSUE TITLE
Type cast exception in SurgicalDebugFilter @ line 74

### ISSUE THREAD

**Issue by vtahlani** [Netflix/zuul#283]
Getting exception String can't be cast to URL at line 74 in SurgicalDebugFilter. I tried to set zuul.debug.host to some IP (XX.XX.XX.XX), IP & port (XX.XX.XX.XX:YYYY) and http://XX.XX.XX.XX:YYYY but still getting type cast error.
 
RequestContext.currentContext.routeHost = routeHost.get();

if I replace above with below then it works fine.

RequestContext.getCurrentContext().setRouteHost( new URL(routeHost.get()));

**Comment by AlexWei2013** [comment]
when I write a filter which extended the SurgicalDebugFilter. I have same problem when seted zuul.debug.host="localhost:8080" in property file.

**Comment by vtahlani** [comment]
I have fixed that issue. Please try now.

**Comment by mind-kdas** [comment]
@vtahlani I am still facing exactly the same issue which you reported even now. I am using zuul-core-1.3.0.jar.  I also searched for your commit but could not find it. Could you please recheck the commit and also confirm if the version I am using is correct or not.
